#:schema node_modules/wrangler/config-schema.json
name = "bsky-worker-well-known"
main = "src/index.js"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]


# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[env.production]
    kv_namespaces = [
        { binding = "STORE", id = "3409a1137dbf499d84197d8a78b6d961" }
    ]
[env.production.vars]
    identifiers = "desu.cx=did:plc:jwj6kf4xowjc5taykzoadxll"

[env.dev]
    kv_namespaces = [
        { binding = "STORE", id = "0b3b9b6195f34f1b8b11e6bd5afafc01" }
    ]
[env.dev.vars]
    identifiers = "example.com=did:plc:jwj6kf4xowjc5taykzoadxll;localhost=did:plc:jwj6kf4xowjc5taykzoadxll"
    DEBUG = true